// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///  options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```flutte
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
  
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetLmthp_x7-eAcXfAg-VkGVVBI1997mc',
    appId: '1:183183889944:android:e3de48f9a8ff684b6a156d',
    messagingSenderId: '183183889944',
    projectId: 'fitx-2154d',
storageBucket: 'fitx-2154d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcSuNpORxhrYweYyFzIQNFJmTPEwS_sto',
    appId: '1:183183889944:ios:13a1acff553012046a156d',
    messagingSenderId: '183183889944',
    projectId: 'fitx-2154d',
storageBucket: 'fitx-2154d.appspot.com',
    iosBundleId: 'com.ddhealthcare.fitx',
  );

}
